In [1]:
import xarray
import numpy as np
import pandas as pd

In [3]:
latitude = np.arange(20, 50.5, 0.5)
longitude = np.arange(-125, -65.5, 0.5)

print(np.shape(latitude), np.shape(longitude))

(61,) (119,)


In [5]:
levels = np.array([1000, 850, 500, 250])
print(np.shape(levels))

(4,)


In [6]:
times = pd.date_range(start='2/23/21 00:00:00', end='2/23/21 23:00:00', freq='H')
print(np.shape(times))

(24,)


In [7]:
temperature = np.random.random((24, 4, 61, 119))
print(np.shape(temperature))

(24, 4, 61, 119)


In [8]:
heights = np.array([0, 500, 1000, 1500, 2000])
print(np.shape(heights))

(5,)


In [10]:
wind_speed = np.random.random((24, 5, 61, 119))
print(np.shape(wind_speed))

(24, 5, 61, 119)


In [13]:
temperature_da = xarray.DataArray(temperature, coords=(times, levels, latitude, longitude),
                                  dims=['time', 'level', 'latitude', 'longitude'])

temperature_da.name = 'Air Temperature'
temperature_da.attrs['units'] = 'degC'

In [18]:
wind_speed_da = xarray.DataArray(wind_speed, coords=(times, heights, latitude, longitude),
                                 dims=['time', 'level', 'latitude', 'longitude'])

wind_speed_da.name = 'Wind Speed'
wind_speed_da.attrs['units'] = 'knots'

In [19]:
wind_speed_da

<xarray.DataArray 'Wind Speed' (time: 24, level: 5, latitude: 61, longitude: 119)>
array([[[[3.00923157e-02, 4.03397841e-01, 7.94892950e-01, ...,
          7.89181290e-01, 4.03206953e-01, 3.12578846e-01],
         [5.32783898e-01, 9.78583195e-01, 8.33595349e-01, ...,
          7.92413240e-01, 4.25823082e-01, 3.30693908e-01],
         [9.65017218e-01, 7.42736573e-02, 3.48808493e-01, ...,
          2.78392701e-01, 3.61165345e-01, 5.14673282e-01],
         ...,
         [3.87556660e-01, 8.86289520e-01, 3.26851716e-01, ...,
          7.84327652e-02, 3.69135152e-01, 5.21471892e-01],
         [4.77096167e-01, 7.51749552e-01, 1.22347239e-02, ...,
          7.40725904e-01, 4.80830212e-01, 3.98043277e-01],
         [5.02035019e-01, 8.40968629e-01, 9.19210538e-01, ...,
          6.73747552e-01, 7.21994086e-01, 9.00128409e-01]],

        [[6.65005911e-01, 7.81239254e-01, 6.99180852e-01, ...,
          5.71534128e-01, 7.80157750e-01, 2.91347258e-01],
         [9.36399514e-01, 9.40692915e-01, 1.32953220e-01, ...,
          9.35561095e-01, 6.13700460e-02, 8.36636179e-01],
         [3.60359019e-01, 8.95827503e-01, 3.31499173e-01, ...,
          2.69986716e-02, 7.49637513e-01, 6.87278005e-01],
...
         [5.12066976e-01, 9.77899959e-02, 4.86023224e-01, ...,
          7.65139677e-01, 9.46654504e-02, 2.80513664e-01],
         [8.45223736e-01, 6.86523945e-01, 1.11451129e-01, ...,
          3.89268809e-01, 1.70735966e-01, 8.43965352e-01],
         [4.11384365e-01, 3.85098456e-01, 7.56135562e-02, ...,
          4.10902778e-01, 9.66638997e-02, 8.94151701e-01]],

        [[8.13522977e-01, 9.53734853e-01, 9.05000991e-02, ...,
          5.49306410e-01, 7.20392814e-01, 1.17778079e-01],
         [8.43684300e-01, 5.88009711e-01, 5.12854931e-01, ...,
          8.82349388e-01, 1.04035889e-01, 3.07003221e-01],
         [5.56554187e-01, 2.56557583e-01, 1.24411474e-02, ...,
          3.59177702e-01, 6.92438689e-01, 1.69769676e-01],
         ...,
         [2.25554353e-03, 4.00822017e-01, 3.84463277e-03, ...,
          2.62593066e-01, 4.42740273e-01, 6.27371426e-01],
         [2.51079278e-01, 9.14394589e-01, 4.26799867e-01, ...,
          1.99916832e-01, 4.50723630e-01, 5.99687479e-01],
         [6.71480747e-01, 5.02023705e-01, 8.04774649e-01, ...,
          2.11625357e-01, 1.59898962e-01, 9.01930413e-01]]]])
Coordinates:
  * time       (time) datetime64[ns] 2021-02-23 ... 2021-02-23T23:00:00
  * level      (level) int64 0 500 1000 1500 2000
  * latitude   (latitude) float64 20.0 20.5 21.0 21.5 ... 48.5 49.0 49.5 50.0
  * longitude  (longitude) float64 -125.0 -124.5 -124.0 ... -67.0 -66.5 -66.0
Attributes:
    units:    knots

In [25]:
ds = xarray.Dataset({'air_temperature': (['time', 'level', 'latitude', 'longitude'], temperature_da),
                     'wind_speed': (['time', 'height', 'latitude', 'longitude'], wind_speed_da)},
                    coords={'time': times, 'level': levels, 'height': heights,
                            'latitude': latitude, 'longitude': longitude})

ds['attrs'] = 'My Custom Model'

In [26]:
ds

<xarray.Dataset>
Dimensions:          (height: 5, latitude: 61, level: 4, longitude: 119, time: 24)
Coordinates:
  * time             (time) datetime64[ns] 2021-02-23 ... 2021-02-23T23:00:00
  * level            (level) int64 1000 850 500 250
  * height           (height) int64 0 500 1000 1500 2000
  * latitude         (latitude) float64 20.0 20.5 21.0 21.5 ... 49.0 49.5 50.0
  * longitude        (longitude) float64 -125.0 -124.5 -124.0 ... -66.5 -66.0
Data variables:
    air_temperature  (time, level, latitude, longitude) float64 0.3265 ... 0....
    wind_speed       (time, height, latitude, longitude) float64 0.03009 ... ...
    attrs            <U15 'My Custom Model'

In [27]:
single_time_temps = ds['air_temperature'].sel(time='2021-02-23 13:00:00', level=500)

In [28]:
single_time_temps

<xarray.DataArray 'air_temperature' (latitude: 61, longitude: 119)>
array([[0.66074856, 0.25998129, 0.75682849, ..., 0.87167142, 0.14338466,
        0.83931456],
       [0.68581991, 0.51386521, 0.71717264, ..., 0.0503035 , 0.29747229,
        0.52928516],
       [0.52035874, 0.3017866 , 0.30204552, ..., 0.65106338, 0.16478933,
        0.37295957],
       ...,
       [0.72026745, 0.94113363, 0.23370513, ..., 0.90894372, 0.57224034,
        0.60480385],
       [0.84514605, 0.24790893, 0.29604616, ..., 0.39475405, 0.29512295,
        0.63532923],
       [0.81250009, 0.67999213, 0.61692123, ..., 0.62903861, 0.0584296 ,
        0.23293624]])
Coordinates:
    time       datetime64[ns] 2021-02-23T13:00:00
    level      int64 500
  * latitude   (latitude) float64 20.0 20.5 21.0 21.5 ... 48.5 49.0 49.5 50.0
  * longitude  (longitude) float64 -125.0 -124.5 -124.0 ... -67.0 -66.5 -66.0

In [30]:
ds['air_temperature'].sel(time='2021-02-23 16:00:00')

<xarray.DataArray 'air_temperature' (level: 4, latitude: 61, longitude: 119)>
array([[[0.84702991, 0.99934407, 0.2784308 , ..., 0.68003322,
         0.75634247, 0.65907781],
        [0.87311888, 0.30712339, 0.12572764, ..., 0.13141349,
         0.62831273, 0.65323668],
        [0.60143792, 0.3702843 , 0.80489794, ..., 0.39059407,
         0.47341925, 0.35407979],
        ...,
        [0.91172794, 0.91380489, 0.35921227, ..., 0.47482593,
         0.41287747, 0.53945944],
        [0.66539419, 0.00473958, 0.37134002, ..., 0.63348051,
         0.69885702, 0.45589946],
        [0.07588287, 0.61798655, 0.87785875, ..., 0.79725399,
         0.22508191, 0.42191344]],

       [[0.56170768, 0.63551815, 0.96257428, ..., 0.32572222,
         0.38344262, 0.40791503],
        [0.77934091, 0.6750575 , 0.22498982, ..., 0.82381352,
         0.25257069, 0.153792  ],
        [0.31189365, 0.42536179, 0.91410428, ..., 0.12232203,
         0.66520784, 0.87878309],
...
        [0.87626735, 0.50325114, 0.79632769, ..., 0.83123431,
         0.26200612, 0.09350175],
        [0.23869489, 0.64080254, 0.54943689, ..., 0.89456473,
         0.13893838, 0.45005661],
        [0.10857937, 0.89002217, 0.68997864, ..., 0.13865037,
         0.69726688, 0.76176872]],

       [[0.80938515, 0.2199459 , 0.23820841, ..., 0.42248165,
         0.2227883 , 0.42135953],
        [0.66837075, 0.8188993 , 0.95448487, ..., 0.18629203,
         0.42064271, 0.10799534],
        [0.44980788, 0.31024749, 0.72495926, ..., 0.88308577,
         0.08359245, 0.0854373 ],
        ...,
        [0.47658069, 0.74855728, 0.24017939, ..., 0.81573902,
         0.45717347, 0.68271807],
        [0.26227565, 0.42748469, 0.20006562, ..., 0.020315  ,
         0.98918707, 0.72965329],
        [0.21914316, 0.7243831 , 0.76808422, ..., 0.64706692,
         0.77611108, 0.59674784]]])
Coordinates:
    time       datetime64[ns] 2021-02-23T16:00:00
  * level      (level) int64 1000 850 500 250
  * latitude   (latitude) float64 20.0 20.5 21.0 21.5 ... 48.5 49.0 49.5 50.0
  * longitude  (longitude) float64 -125.0 -124.5 -124.0 ... -67.0 -66.5 -66.0

In [31]:
ds['air_temperature'].sel(latitude=40, longitude=-75).isel(level=0)

<xarray.DataArray 'air_temperature' (time: 24)>
array([0.99993287, 0.41762189, 0.5148031 , 0.10540315, 0.60449302,
       0.54447268, 0.25867071, 0.5571875 , 0.2118064 , 0.00822178,
       0.03937652, 0.43018575, 0.36487433, 0.77424157, 0.93084344,
       0.13957618, 0.36790295, 0.0492639 , 0.09126732, 0.22405758,
       0.37570733, 0.25999195, 0.15749634, 0.30206636])
Coordinates:
  * time       (time) datetime64[ns] 2021-02-23 ... 2021-02-23T23:00:00
    level      int64 1000
    latitude   float64 40.0
    longitude  float64 -75.0

In [35]:
import matplotlib.pyplot as plt

In [36]:
plt.plot(ds['air_temperature'].sel(latitude=40, longitude=-75).isel(level=0))